#docker build -t rendl.net:5000/sct_db-data:1.0 images/db-data
data:
    image: rendl.net:5000/sct_db-data:1.0

#docker build -t rendl.net:5000/sct_db:1.0 images/db-mariadb
db:
    image: rendl.net:5000/sct_db:1.0
    hostname: db
    tty: true
    restart: always
    environment:
        - "LC_ALL=C.UTF-8"
    volumes_from:
        - data
    ports:
        - "9306:3306"

#docker build -t rendl.net:5000/sct_web:1.0 images/web-nginx
web:
    image: rendl.net:5000/sct_web:1.0
    hostname: web
    tty: true
    restart: always
    environment:
        - "LC_ALL=C.UTF-8"
    volumes: 
        - "volumes/nginx-sites-enabled:/etc/nginx/sites-enabled"
    volumes_from:
        - app
    links:
        - app
    ports:
        - "9080:80"
        - "9081:443"

#docker build -t rendl.net:5000/sct_app-php:1.0 images/app-php
app:
    image: rendl.net:5000/sct_app-php:1.0
    hostname: app
    tty: true
    restart: always
    environment:
        - "LC_ALL=C.UTF-8"
    volumes:
        - "volumes/web-projects:/var/www"
        - "volumes/etc-php:/usr/local/etc/php"
        - "volumes/php-extensions:/usr/local/lib/php/extensions"
    links:
        - db
    ports:
        - "8000:8000"

