services:
    sctiengen_website.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - SCTiengenWebSiteBundle Basepaths
            - [ "/cms/routes" ]
        tags:
            - { name: "doctrine_phpcr.initializer" }
    sctiengen_website.block.markdown:
        class: SCTiengen\WebSiteBundle\Block\MarkdownBlockService
        arguments:
            - "sctiengen_website.block.markdown"
            - "@templating"
        tags:
            - { name: "sonata.block" }
    sctiengen_website.menu.voter:
        class: SCTiengen\WebSiteBundle\Menu\CurrentMenuItemVoter
        calls:
            - [ setRequestStack, [ "@request_stack" ] ]
        tags:
            - { name: "cmf_menu.voter" }

