services:
#    sc_tiengen_web_site.example:
#        class: SCTiengen\WebSiteBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sctiengen_website.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - SCTiengenWebSiteBundle Basepaths
            - [ "/cms/routes" ]
        tags:
            - { name: "doctrine_phpcr.initializer" }
    sctiengen_website.block.markdown:
        class: SCTiengen\WebSiteBundle\Block\MarkdownBlockService
        arguments:
            - "sctiengen_website.block.markdown"
            - "@templating"
        tags:
            - {name: "sonata.block"}