services:
    sctiengen_website.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - SCTiengenWebSiteBundle Basepaths
            - [ "/cms/routes" ]
        tags:
            - { name: "doctrine_phpcr.initializer" }
    sctiengen_website.block.markdown:
        class: SCTiengen\WebSiteBundle\Block\MarkdownBlockService
        arguments:
            - "sctiengen_website.block.markdown"
            - "@templating"
        tags:
            - { name: "sonata.block" }
    sctiengen_website.menu.voter:
        class: SCTiengen\WebSiteBundle\Menu\CurrentMenuItemVoter
        calls:
            - [ setRequestStack, [ "@request_stack" ] ]
        tags:
            - { name: "cmf_menu.voter" }
    
    sctiengen_website.form.type.download_file:
        class: SCTiengen\WebSiteBundle\Form\Type\DownloadFileType
        arguments:
            - Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\File
            - "@cmf_media.upload_file_helper"
        tags:
            - { name: "form.type", alias: "download_file" }
    
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    
