sctiengen_news_list:
    path:     /
    defaults: { _controller: SCTiengenNewsBundle:Default:list }

sctiengen_news_detail:
    path:     /{name}
    defaults: { _controller: SCTiengenNewsBundle:Default:detail }
