services:
    sctiengen_news.admin.news_message:
        class: SCTiengen\NewsBundle\Admin\NewsMessageAdmin
        arguments: [null, SCTiengen\NewsBundle\Entity\NewsMessage, SCTiengenNewsBundle:NewsMessageAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: news, label: "List" }
