imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @SCTiengenWebSiteBundle/Resources/config/admin.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [CmfCreateBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration (needed for Jackalope Doctrine DBAL)
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        path:     "%database_path%"
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    SCTiengenNewsBundle:  ~

# Doctrine PHPCR-ODM configuration
doctrine_phpcr:
    session:
        backend: "%phpcr_backend%"
        workspace: "%phpcr_workspace%"
        username: "%phpcr_user%"
        password: "%phpcr_password%"
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"

# Jackalope Metadata and Node Cache services
doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

cmf_block:
    persistence:
        phpcr:
            imagine_document_class:   SCTiengen\WebSiteBundle\Document\ImageBlock
            
cmf_content:
    persistence:
        phpcr:
            admin_class:      SCTiengen\WebSiteBundle\Admin\PageAdmin
            document_class:   SCTiengen\WebSiteBundle\Document\Page

# Cmf Configuration
cmf_core:
    persistence:
        phpcr: true
        # if you want another basepath
        # basepath: /custom/basepath
    publish_workflow: false

# Cmf Routing Configuration
cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with a low priority
            # this way the non dynamic routes take precedence
            # to prevent needless database look ups
            cmf_routing.dynamic_router: 20
            # enable the symfony default router with a higher priority
            router.default: 100
    dynamic:
        controllers_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent: cmf_content.controller::indexAction
            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute: cmf_routing.redirect_controller:redirectAction
        templates_by_class:
            SCTiengen\WebSiteBundle\Document\Page: SCTiengenWebSiteBundle:Page:standard.html.twig
        persistence:
            phpcr:
                route_basepath: /cms/routes
                use_sonata_admin: true

sonata_seo:
    page:
        title: SC Freiburg-Tiengen

cmf_seo:
    title: %%content_title%% - SC Freiburg-Tiengen
    description: %%content_description%%

# Menu Configuration
knp_menu:
    twig: true

liip_imagine:
    filter_sets:
        cmf_block:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [616, 419], mode: outbound }
        image_upload_thumbnail:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts: [admin]

sonata_admin:
    extensions:
        cmf_core.admin_extension.child:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Model\ChildInterface
                - Doctrine\ODM\PHPCR\HierarchyInterface
        cmf_menu.admin_extension.menu_node_referrers:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
        cmf_menu.admin_extension.menu_options:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuOptionsInterface
        sctiengen_website.admin_extension.renderhints:
            implements:
                - SCTiengen\WebSiteBundle\Document\RenderHinted
        cmf_seo.admin_extension:
            implements:
                - Symfony\Cmf\Bundle\SeoBundle\SeoAwareInterface
    dashboard:
        blocks:
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
            - { position: right, type: sonata.admin.block.admin_list }
        groups:
            content:
                label: Content
                items:
                    - sctiengen_website.admin.page
                    - cmf_block.container_admin
                    - sctiengen_website.admin.markdown
                    - cmf_block.imagine.imagine_admin
                    - cmf_block.imagine.slideshow_admin
                    #- cmf_block.simple_admin
                    #- cmf_block.string_admin
                    - cmf_block.menu_admin
                    - cmf_block.reference_admin
                    - cmf_block.action_admin
            routing:
                label: URLs
                items:
                    - cmf_routing.route_admin
                    - cmf_routing.redirect_route_admin
            menu:
                label: Menu
                items:
                    - cmf_menu.menu_admin
                    - cmf_menu.node_admin

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        SCTiengen\WebSiteBundle\Document\Page:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - SCTiengen\WebSiteBundle\Document\Page
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock
                - SCTiengen\WebSiteBundle\Document\ImageBlock
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock:
            valid_children:
                - SCTiengen\WebSiteBundle\Document\MarkdownBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock
                - SCTiengen\WebSiteBundle\Document\ImageBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\MenuBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\StringBlock
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock:
            valid_children: []
        SCTiengen\WebSiteBundle\Document\ImageBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\MenuBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\StringBlock:
            valid_children: []
        SCTiengen\WebSiteBundle\Document\MarkdownBlock:
            valid_children: []
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route:
            valid_children:
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:
            valid_children: []
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\Menu:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode

# Cmf Create Configuration
fos_rest:
    view:
        formats:
            json: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

