parameters:
    calendar_service.app_name: "SCTiengenWebsite"
    calendar_service.service_account_credentials: "%kernel.root_dir%/config/calendar_service_account.json"

services:
    sctiengen_calendar_view.calendar_proxy:
        class: SCTiengen\CalendarViewBundle\Google\CalendarProxy
        calls:
            - [ setAppName, [ "%calendar_service.app_name%" ] ]
            - [ setServiceAccountCredentialsFile, [ "%calendar_service.service_account_credentials%" ] ]
    
    sctiengen_calendar_view.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: [ "@doctrine", getManager ]
    
    sctiengen_calendar_view.calendar_sync_manager:
        class: SCTiengen\CalendarViewBundle\Google\Sync\CalendarManager
        calls:
            - [ setLogger, [ "@monolog.logger.calendar_view" ] ]
            - [ setCalendarProxy, [ "@sctiengen_calendar_view.calendar_proxy" ] ]
            - [ setEntityManager, [ "@sctiengen_calendar_view.entity_manager" ] ]
    
